services:
  lstm-detector:
    build:
      context: ./app
    container_name: lstm-detector
    restart: always
    volumes:
      - ./app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    command: python main.py
    environment:
      - PROMETHEUS_URL=http://192.168.111.111:9090
      - ALERT_ENDPOINT=http://alert-api:5000/alert
      #- NVIDIA_VISIBLE_DEVICES=all
    #runtime: nvidia
    depends_on:
      - alert-api

  alert-api:
    build:
      context: ./flaskAPI
    container_name: alert-api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./flaskAPI:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    environment:
      - ALERTMANAGER_URL=http://192.168.111.111:9093/api/v1/alerts
