services:
  lstm-detector:
    build: ./app
    container_name: lstm-detector
    restart: always
    volumes:
      - ./app:/app
    environment:
      - PROMETHEUS_URL=http://192.168.111.111:9090
      - ALERT_ENDPOINT=http://alert-api:5001/alert
      - LOG_LEVEL=INFO
    networks:
      - ai-monitoring-net
    depends_on:
      - alert-api

  alert-api:
    build: ./flaskAPI
    container_name: alert-api
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./flaskAPI:/app
      - /home/tungn/AIagent/data/rag_processed:/rag_source:ro
    environment:
      - RAG_API_URL=http://172.27.119.158:5005/ask
      - ALERTMANAGER_URL=http://192.168.111.111:9093/api/v1/alerts
      - ELK_URL=http://192.168.111.111:9200
      - SRE_AGENT_URL=http://sre-agent:5002/execute
      - LOG_LEVEL=INFO
    networks:
      - ai-monitoring-net

  log-watcher:
    build: ./logWatcher
    container_name: log-watcher
    restart: always
    volumes:
      - ./logWatcher:/app
    environment:
      - ELK_URL=http://192.168.111.111:9200
      - ALERT_ENDPOINT=http://alert-api:5001/alert
      - LOG_LEVEL=INFO
      - LOG_WATCHER_KEYWORDS=error,timeout,denied,failed,exception,upstream timed out,refused
    networks:
      - ai-monitoring-net
    depends_on:
      - alert-api

  sre-agent:
    build: ./sre_agent
    container_name: sre-agent
    restart: always
    volumes:
      - ./sre_agent:/app
      - ./sre_agent/ssh_keys/id_rsa:/app/ssh_keys/id_rsa:ro
    environment:
      - SSH_USER=vagrant
      - ANSIBLE_CONTROLLER_IP=192.168.111.111
      - SSH_KEY_PATH=/app/ssh_keys/id_rsa
      - LOG_LEVEL=INFO
    networks:
      - ai-monitoring-net

networks:
  ai-monitoring-net:
    driver: bridge

