services:

  lstm-detector:
    build: ./app
    container_name: lstm-detector
    restart: always
    volumes:
      - ./app:/app
    environment:
      - PROMETHEUS_URL=http://192.168.111.111:9090
      - ALERT_ENDPOINT=http://alert-api:5001/alert
      - LOG_LEVEL=INFO
    networks:
      - ai-monitoring-net
    depends_on:
      - alert-api

  alert-api:
    build: ./flaskAPI
    container_name: alert-api
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./flaskAPI:/app
      - ./flaskAPI/ai_suggestions:/app/ai_suggestions  # ✅ SỬA ĐÚNG ĐƯỜNG DẪN
    environment:
      - ALERTMANAGER_URL=http://192.168.111.111:9093/api/v1/alerts
      - RAG_ENGINE_URL=http://host.docker.internal:5005/ask
      - ELK_URL=http://192.168.111.111:9200
      - LOG_LEVEL=DEBUG
    networks:
      - ai-monitoring-net

  log-watcher:
    build: ./logWatcher
    container_name: log-watcher
    restart: always
    volumes:
      - ./logWatcher:/app
      - ./logWatcher/log_watcher.log:/app/log_watcher.log
    environment:
      - ELK_URL=http://192.168.111.111:9200
      - ALERT_ENDPOINT=http://alert-api:5001/alert
      - LOG_LEVEL=INFO
    networks:
      - ai-monitoring-net
    depends_on:
      - alert-api

networks:
  ai-monitoring-net:
    driver: bridge
